name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.8
  countries_world_map: ^1.3.0
  country_flags: ^2.0.2
  image_picker: ^1.2.1
  path_provider: ^2.1.1
  path: ^1.9.0
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.4
  firebase_core: ^3.10.1
  http: ^1.6.0
  shared_preferences: ^2.2.2
  home_widget: ^0.7.0
  flutter_colorpicker: ^1.1.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/wmap_icon_v3.png"
  adaptive_icon_background: "assets/images/wmap_icon_v3.png"
  min_sdk_android: 21  

flutter_native_splash:
  color: "#5170ff" 
  image: "assets/images/splash.png"
  
  fullscreen: false 

  android_12:
    image: "assets/images/splash.png"
    color: "#5170ff" 
    icon_background_color: "#5170ff"
    

flutter:
  uses-material-design: true
  assets:
    - assets/images/


